name: 6dof_bot
dof: 6

# pi/2 = 1.5707963267948966
# pi = 3.141592653589793
# 3pi/2 = 4.71238898038469

# TODO: add joint limits per joint (min_angle, max_angle in radians)

home_position: [0, 0, 0, 0, 0, 0]  # one value per joint, in radians (revolute) or meters (prismatic)

joints:
  -
    type: revolute
    a: 0 
    alpha: 0 
    d: 1
    theta: 1.57079
    geometry: cylinder
    mass: 2
    length: 1
    radius: 0.1
    
  -
    type: prismatic
    a: 1
    alpha: 1.57079
    d: 0 
    theta: 0
    geometry: cylinder
    mass: 2
    length: 0.5
    radius: 0.1
  -
    type: revolute
    a: 0
    alpha: 0 
    d: 2
    theta: 0
    geometry: cylinder
    mass: 2
    length: 2
    radius: 0.1
  -
    type: prismatic
    a: 0
    alpha: 1.57079
    d: 0
    theta: 0
    geometry: cylinder
    mass: 2
    length: 0.25
    radius: 0.1  
  -
    type: revolute
    a: 0
    alpha: 0 
    d: 0.5 
    theta: 1.57079
    geometry: cylinder
    mass: 2
    length: 0.5
    radius: 0.1
  -
    type: revolute
    a: 0
    alpha: 1.57079
    d: 0.5
    theta: 0
    geometry: cylinder
    mass: 2
    length: 0.5
    radius: 0.1